=== pnp/sp-dev-fx-aces/templates/metadata-schema.json
{
  "$id": "https://developer.microsoft.com/en-us/json-schemas/pnp/samples/v1.0/metadata-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
          "name": {
              "type": "string",
              "pattern": "pnp-sp-fx-aces-.*"
          },
          "version": {
              "type": "string"
          },
          "source": {
              "type": "string",
              "default": "pnp",
              "pattern": "pnp"
          },
          "title": {
              "type": "string"
          },
          "url": {
              "type": "string",
              "pattern": "https:\/\/github.com\/pnp\/sp-dev-fx-aces\/tree\/main\/(samples|scenarios)\/.*"
          },
          "creationDateTime": {
              "type": "string",
              "format": "date"
          },
          "updateDateTime": {
              "type": "string",
              "format": "date"
          },
          "shortDescription": {
              "type": "string"
          },
          "longDescription": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "products": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "categories": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "metadata": {
              "type": "array",
              "items": {
                  "type": "object",
                  "properties": {
                      "key": {
                          "type": "string"
                      },
                      "value": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "key",
                      "value"
                  ]
              }
          },
          "thumbnails": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "type": {
                              "type": "string",
                              "enum": [
                                  "image",
                                  "video",
                                  "slideshow"
                              ]
                          },
                          "order": {
                              "type": "integer"
                          },
                          "alt": {
                              "type": "string"
                          }
                      },
                      "if": {
                          "properties": {
                              "type": {
                                  "const": "slideshow"
                              }
                          }
                      },
                      "then": {
                          "properties": {
                              "slides": {
                                  "type": "array",
                                  "items": {
                                      "type": "object",
                                      "properties": {
                                          "url": {
                                              "type": "string"
                                          },
                                          "order": {
                                              "type": "integer"
                                          },
                                          "alt": {
                                              "type": "string"
                                          }
                                      },
                                      "required": [
                                          "url",
                                          "order",
                                          "alt"
                                      ]
                                  }
                              }
                          },
                          "required": [
                              "slides"
                          ]
                      },
                      "else": {
                          "properties": {
                              "url": {
                                  "type": "string"
                              }
                          },
                          "required": [
                              "url"
                          ]
                      },
                      "required": [
                          "type",
                          "order",
                          "alt"
                      ]
                  }
              ]
          },
          "authors": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "gitHubAccount": {
                              "type": "string",
                              "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
                          },
                          "company": {
                              "type": "string"
                          },
                          "pictureUrl": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "gitHubAccount"
                      ]
                  }
              ]
          },
          "references": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "name": {
                              "type": "string"
                          },
                          "description": {
                              "type": "string"
                          },
                          "url": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "name",
                          "url"
                      ]
                  }
              ]
          }
      },
      "required": [
          "name",
          "source",
          "title",
          "url",
          "shortDescription",
          "products",
          "metadata",
          "thumbnails",
          "authors",
          "creationDateTime",
          "updateDateTime"
      ]
  }
}

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-RecentFiles/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-recentfiles",
  "source": "pnp",
  "title": "Recent files",
  "shortDescription": "Viva Connection Adaptive Card Extension (ACE) that shows the recent files for the current user.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-RecentFiles",
  "longDescription": [
    "Viva Connection Adaptive Card Extension (ACE) that shows the recent files for the current user."
  ],
  "creationDateTime": "2022-04-11",
  "updateDateTime": "2022-04-11",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.14.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-RecentFiles/assets/QuickViewAndCardView.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "GuidoZam",
    "pictureUrl": "https://github.com/GuidoZam.png",
    "name": "Guido Zambarda"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-Covid-Indicator/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-covid-indicator",
  "source": "pnp",
  "title": "COVID-19 Indicator",
  "shortDescription": "This Adaptive Card Extension displays COVID-19 data from the specified country.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-Covid-Indicator",
  "longDescription": [
    "This Adaptive Card Extension allows the user to select a country and display real-time COVID-19 related data in the card. In the QuickView it displays additional data such as total population, severity of cases, and deaths."
  ],
  "creationDateTime": "2021-12-12",
  "updateDateTime": "2021-12-12",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.1"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-Covid-Indicator/assets/demo.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "joaojmendes",
    "pictureUrl": "https://github.com/joaojmendes.png",
    "name": "Jo√£o Mendes"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/BasicCard-SharePoint-CRUD/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-sharepoint-crud",
  "source": "pnp",
  "title": "SharePoint CRUD Example",
  "shortDescription": "This Adaptive Card Extension shows how to work with form elements and form data in an Adaptive Card. It is an example of how to use an ACE to interact with SharePoint List data using PnPJS.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/BasicCard-SharePoint-CRUD",
  "longDescription": [
    "This ACE shows how to work with different form elements to collect and display data from an Adaptive Card and store that data in a SharePoint list. A sample list is provisioned when the ACE is loaded for the first time. It also shows how to navigate from one view to another with multiple cards."
  ],
  "creationDateTime": "2022-01-13",
  "updateDateTime": "2022-01-13",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/BasicCard-SharePoint-CRUD/assets/demo.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "dcashpeterson",
    "company": "Sympraxis Consulting",
    "pictureUrl": "https://github.com/dcashpeterson.png",
    "name": "Derek Cash-Peterson",
    "twitter": "spdcp"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-Follow-Documents/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-ace-followdocument",
  "source": "pnp",
  "title": "Follow Documents",
  "shortDescription": "Adaptive Card showing Followed Documents",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-Follow-Documents",
  "longDescription": [
    "ACE showing documents the current user follows. Allows the user to see a preview, view document metadata, share via Teams, and download the document."
  ],
  "creationDateTime": "2021-12-01",
  "updateDateTime": "2021-12-01",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-Follow-Documents/assets/demo.gif",
    "alt": "Follow Document demo"
  }],
  "authors": [{
    "gitHubAccount": "aaclage",
    "company": "Datalynx AG",
    "pictureUrl": "https://github.com/aaclage.png",
    "name": "Andr√© Lage",
    "twitter": "aaclage"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-Graph-JoinNewTeams/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-joinnewteam",
  "source": "pnp",
  "title": "Join New Team",
  "shortDescription": "This Adaptive Card Extension shows public Teams the user is not a member of and allows them to join the Team.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-Graph-JoinNewTeams",
  "longDescription": [
    "This Adaptive Card Extension shows how to us the Microsoft Graph to pull the list of teams for a tenant and how to programmatically add a user to the team."
  ],
  "creationDateTime": "2022-02-28",
  "updateDateTime": "2022-02-28",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.1"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-Graph-JoinNewTeams/assets/Demo1.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "a1mery",
    "pictureUrl": "https://github.com/a1mery.png",
    "name": "Aimery Thomas"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/ImageCard-At-a-glance/assets/sample.json
[
  {
    "name": "pnp-sp-fx-aces-ace-articlecontent",
    "source": "pnp",
    "title": "Article Content at a glance",
    "shortDescription": "Adaptive Card displays of Article Content",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/master/samples/ImageCard-At-a-glance",
    "longDescription": [
      "ACE with multiple card views to show the first few sentences of an article in a SharePoint site"
    ],
    "creationDateTime": "2021-10-06",
    "updateDateTime": "2021-10-06",
    "products": [
      "SharePoint",
      "Office",
      "Viva"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.13.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://github.com/pnp/sp-dev-fx-aces/raw/main/samples/ImageCard-At-a-glance/assets/demo.gif",
        "alt": "London Transport"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "anoopt",
        "company": "Content+Cloud",
        "pictureUrl": "https://github.com/anoopt.png",
        "name": "Anoop Tatti",
        "twitter": "anooptells"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/samples/ImageCard-HybridWork-Checkin/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-hybridwork-checkin",
  "source": "pnp",
  "title": "Hybrid Work Employee Check-in Adaptive Card Extension",
  "shortDescription": "Adaptive Card Extension that allows users to check in to the office.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-HybridWork-Checkin",
  "longDescription": [
    "Adaptive Card Extension that allows users to check in for a desk in an office building. Stores data in a SharePoint list."
  ],
  "creationDateTime": "2021-11-08",
  "updateDateTime": "2021-11-08",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.github.com/pnp/sp-dev-fx-aces/main/samples/ImageCard-HybridWork-Checkin/assets/demo.gif",
    "alt": "Hybrid Work Employee Check-In"
  }],
  "authors": [{
    "gitHubAccount": "ArijitCloud",
    "company": "",
    "pictureUrl": "https://github.com/ArijitCloud.png",
    "name": "Arijit Mondal",
    "twitter": ""
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/ImageCard-Rss/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-rss",
  "source": "pnp",
  "title": "Adaptive Card Extension PnP Weekly Feed",
  "shortDescription": "This ACE displays the PnP Weekly video recording RSS feed. ",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-Rss",
  "longDescription": [
    "This ACEs accesses the RSS feed from PnP Weekly and display episodes, audio and description as slider with search capability of description."
  ],
  "creationDateTime": "2022-01-27",
  "updateDateTime": "2022-01-27",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/ImageCard-Rss/assets/PnPWeekly.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "aaclage",
    "company": "Datalynx AG",
    "pictureUrl": "https://github.com/aaclage.png",
    "name": "Andr√© Lage",
    "twitter": "aaclage"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]
