=== pnp/sp-dev-fx-aces/templates/metadata-schema.json
{
  "$id": "https://developer.microsoft.com/en-us/json-schemas/pnp/samples/v1.0/metadata-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
          "name": {
              "type": "string",
              "pattern": "pnp-sp-fx-aces-.*"
          },
          "version": {
              "type": "string"
          },
          "source": {
              "type": "string",
              "default": "pnp",
              "pattern": "pnp"
          },
          "title": {
              "type": "string"
          },
          "url": {
              "type": "string",
              "pattern": "https:\/\/github.com\/pnp\/sp-dev-fx-aces\/tree\/main\/(samples|scenarios)\/.*"
          },
          "creationDateTime": {
              "type": "string",
              "format": "date"
          },
          "updateDateTime": {
              "type": "string",
              "format": "date"
          },
          "shortDescription": {
              "type": "string"
          },
          "longDescription": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "products": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "categories": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "metadata": {
              "type": "array",
              "items": {
                  "type": "object",
                  "properties": {
                      "key": {
                          "type": "string"
                      },
                      "value": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "key",
                      "value"
                  ]
              }
          },
          "thumbnails": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "type": {
                              "type": "string",
                              "enum": [
                                  "image",
                                  "video",
                                  "slideshow"
                              ]
                          },
                          "order": {
                              "type": "integer"
                          },
                          "alt": {
                              "type": "string"
                          }
                      },
                      "if": {
                          "properties": {
                              "type": {
                                  "const": "slideshow"
                              }
                          }
                      },
                      "then": {
                          "properties": {
                              "slides": {
                                  "type": "array",
                                  "items": {
                                      "type": "object",
                                      "properties": {
                                          "url": {
                                              "type": "string"
                                          },
                                          "order": {
                                              "type": "integer"
                                          },
                                          "alt": {
                                              "type": "string"
                                          }
                                      },
                                      "required": [
                                          "url",
                                          "order",
                                          "alt"
                                      ]
                                  }
                              }
                          },
                          "required": [
                              "slides"
                          ]
                      },
                      "else": {
                          "properties": {
                              "url": {
                                  "type": "string"
                              }
                          },
                          "required": [
                              "url"
                          ]
                      },
                      "required": [
                          "type",
                          "order",
                          "alt"
                      ]
                  }
              ]
          },
          "authors": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "gitHubAccount": {
                              "type": "string",
                              "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
                          },
                          "company": {
                              "type": "string"
                          },
                          "pictureUrl": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "gitHubAccount"
                      ]
                  }
              ]
          },
          "references": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "name": {
                              "type": "string"
                          },
                          "description": {
                              "type": "string"
                          },
                          "url": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "name",
                          "url"
                      ]
                  }
              ]
          }
      },
      "required": [
          "name",
          "source",
          "title",
          "url",
          "shortDescription",
          "products",
          "metadata",
          "thumbnails",
          "authors",
          "creationDateTime",
          "updateDateTime"
      ]
  }
}

=== pnp/sp-dev-fx-aces/samples/ImageCard-OfficeLocations/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-officelocations",
  "source": "pnp",
  "title": "Office Locations",
  "shortDescription": "This sample shows how to build an ACE with multiple card views to show the details of the offices in an organization.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-OfficeLocations",
  "longDescription": [
    "This sample shows how to build an ACE with a PrimaryText card view and a quick view to display current logged in user's immediate upcoming shift in card view and all upcoming shifts in Quick view."
  ],
  "creationDateTime": "2022-02-15",
  "updateDateTime": "2022-06-01",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.14.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/ImageCard-OfficeLocations/assets/ace-demo.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "anoopt",
    "pictureUrl": "https://github.com/anoopt.png",
    "name": "Anoop Tatti"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-PlannerTasks/assets/sample.json
[
  {
    "name": "pnp-sp-fx-aces-ace-plannertasks",
    "source": "pnp",
    "title": "Planner Tasks",
    "shortDescription": "Adaptive Card displays of Planner Tasks",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-PlannerTasks",
    "longDescription": [
      "ACE with a PrimaryText card view and multiple quick views to display the logged-in user Planner Tasks from all associated plans."
    ],
    "creationDateTime": "2021-10-06",
    "updateDateTime": "2021-10-06",
    "products": [
      "SharePoint",
      "Viva"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.13.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-PlannerTasks/assets/demo.gif",
        "alt": "London Transport"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "ejazhussain",
        "company": "Content+Cloud",
        "pictureUrl": "https://github.com/ejazhussain.png",
        "name": "Ejaz Hussain",
        "twitter": "EjazHussain_"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/scenarios/ace-microsoftgraph/assets/sample.json
[
  {
    "name": "pnp-sp-fx-aces-scenario-ace-microsoftgraph",
    "source": "pnp",
    "title": "Microsoft Graph - ACE Scenario",
    "shortDescription": "Starting point on building Microsoft Graph connected ACE extension for Microsoft Viva",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/scenarios/ace-microsoftgraph",
    "longDescription": [
      ""
    ],
    "creationDateTime": "2021-06-10",
    "updateDateTime": "2022-12-09",
    "products": [
      "SharePoint",
      "Viva"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.16.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/scenarios/ace-microsoftgraph/assets/preview.png",
        "alt": "Preview"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "waldekmastykarz",
        "pictureUrl": "https://github.com/waldekmastykarz.png",
        "name": "Waldek Mastykarz"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/samples/ImageCard-my-recent-files/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-my-recent-files",
  "source": "pnp",
  "title": "My Recent Files",
  "shortDescription": "This Adaptive Card Extension allows user quick access recent files",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-my-recent-files",
  "longDescription": [
    "This Adaptive Card Extension allows user quick access recent files"
  ],
  "creationDateTime": "2022-04-12",
  "updateDateTime": "2022-04-12",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.14.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/ImageCard-my-recent-files/assets/demo.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "joaojmendes",
    "company": "VALO Solutions Ltd",
    "pictureUrl": "https://github.com/joaojmendes.png",
    "name": "Jo√£o Mendes",
    "twitter": "joaojmendes"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/ace-cardgallery/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-ace-cardgallery",
  "source": "pnp",
  "title": "Adaptive Cards Sample Gallery",
  "shortDescription": "11 Adaptive Card Extension Samples",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ace-cardgallery",
  "longDescription": [
    "This solution provides a set of eleven (11) Adaptive Card Extensions to demonstrate the various features that can be implemented roughly based on the samples provided by the Adaptive Card documentation."
  ],
  "creationDateTime": "2021-09-28",
  "updateDateTime": "2021-09-28",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.github.com/pnp/sp-dev-fx-aces/main/samples/ace-cardgallery/assets/acegallery.gif",
    "alt": "Gallery of 11 samples"
  }],
  "authors": [{
    "gitHubAccount": "dcashpeterson",
    "company": "Sympraxis Consulting",
    "pictureUrl": "https://github.com/dcashpeterson.png",
    "name": "Derek Cash-Peterson",
    "twitter": "spdcp"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/ImageCard-TodaysLunch/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-todays-lunch",
  "source": "pnp",
  "title": "Today's Lunch Adaptive Card Extension",
  "shortDescription": "Adaptive Card Extension that shows today's lunch.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-TodaysLunch",
  "longDescription": [
    "Adaptive Card Extension that shows the lunch menu for the current day using a SharePoint List and PnPJs"
  ],
  "creationDateTime": "2021-10-28",
  "updateDateTime": "2021-12-13",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/ImaceCard-TodaysLunch/assets/preview.gif",
    "alt": "Today's Lunch ACE"
  }],
  "authors": [{
    "gitHubAccount": "luismanez",
    "company": "ClearPeople",
    "pictureUrl": "https://github.com/luismanez.png",
    "name": "Luis Manez",
    "twitter": "luismanez"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/sample-metadatatemplate.json
[
  {
    "name": "pnp-sp-fx-aces-TODO",
    "source": "pnp",
    "title": "TODO",
    "shortDescription": "TODO",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/TODO",
    "longDescription": [
      "TODO"
    ],
    "creationDateTime": "2021-04-02",
    "updateDateTime": "2021-04-02",
    "products": [
      "SharePoint",
      "Office"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.11.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://github.com/pnp/sp-dev-fx-aces/raw/master/samples/TODO",
        "alt": "TODO"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "TODO",
        "pictureUrl": "https://github.com/TODO.png",
        "name": "TODO",
        "twitter": "TODO"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/samples/BasicCard-StatusMessage/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-statusmessage",
  "source": "pnp",
  "title": "Teams Status ACE Example",
  "shortDescription": "This ACE demonstrates how to use the Presence Graph API endpoints (beta) to set and retrieve a presence status message for a user.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/BasicCard-StatusMessage",
  "longDescription": [
    "This ACE demonstrates how to use the Presence Graph API endpoints (beta) to set and retrieve a presence status message for a user."
  ],
  "creationDateTime": "2022-12-21",
  "updateDateTime": "2022-12-21",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.16.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/BasicCard-StatusMessage/assets/demo.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "yhabersaat",
    "pictureUrl": "https://github.com/yhabersaat.png",
    "name": "Yves Habersaat",
    "twitter": "yhabersaat"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]
